version: "3.5"
services:
  geth:
    build:
      context: ./geth
      args:
        UPSTREAM_VERSION: v1.14.6
    volumes:
      - lukso:/lukso
    ports:
      - 33141:33141/tcp
      - 33141:33141/udp
    restart: unless-stopped
    environment:
      - EXTRA_FLAGS
      - P2P_PORT=33141
      - SYNCMODE=snap
      - GAS_PRICE=1000000000
      - MAX_PEERS=50
    image: geth.lukso-geth.dnp.dappnode.eth:0.1.0
volumes:
  lukso: {}
