version: "3.5"
services:
  lukso:
    image: "lukso.lukso-geth.dnp.dappnode.eth:0.1.0"
    build:
      context: .
      args:
        UPSTREAM_VERSION: v1.10.25
    volumes:
      - "lukso:/lukso"
    ports:
      - "33141:33141/tcp"
      - "33141:33141/udp"
    restart: unless-stopped
    environment:
      - "EXTRA_OPTION=--http.api eth,engine,net,web3,txpool"
      - P2P_PORT=33141
      - SYNCMODE
volumes:
  lukso: {}
